on: pull_request
name: Increment Pixela if Pull Request is opened
jobs:
  filterPRIsOpened:
    name: Filter PR is opened
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Filter PR is opened
      uses: actions/bin/filter@46ffca7632504e61db2d4cb16be1e80f333cb859
      with:
        args: action 'opened|reopened'
    - name: increment pixe.la
      uses: swinton/httpie.action@8ab0a0e926d091e0444fcacd5eb679d2e2d4ab3d
      env:
        PIXELA_PR_INCREMENT_HASH: ${{ secrets.PIXELA_PR_INCREMENT_HASH }}
        PIXELA_USERNAME: ${{ secrets.PIXELA_USERNAME }}
      with:
        args: POST pixe.la/v1/users/$PIXELA_USERNAME/webhooks/$PIXELA_PR_INCREMENT_HASH
